# Configuration for HeadRotate
HeadRotate:
  is-activated: false
  player-not-online: "&b&lSTAFF &8&l» &fPlayer not found"
  usage:
    - "&6_____________.[ &2Head Rotate &6]._____________"
    - "&b/rotate &3[player] &eRotates targeted player's head."
  success-rotate: "&b&lSTAFF &8&l» &fYou have rotated &b%player%'s&f head!"

# Configuration for AntiSkilled
AntiSkilled:
  is-activated: false
  ban-message: "[AUTOMATIC] Log off Skilled v3"
  ban-duration: 10
  bypass-message: "&c&l[ANTISKILLED] &8&l» &fYou bypass this check."

# Configuration for FlyBoostLimiter
flyboostlimiter:
  is-activated: false
  max-x-boost: 2.0   # Max velocity on the X-axis
  max-y-boost: 2.0   # Max velocity on the Y-axis
  exceed-message: "&cYou are flying too fast!"
  alert: "&c&lAlert &7&l» &4%player%&f may be flyboosting."

# Configuration for Anti-Void
Anti-Void:
  is-activated: false
  teleport-location:
    world: world  # CaSe SeNsItIvE
    x: 100.0
    y: 65.0
    z: 100.0
  # List of blocked worlds where this feature won't work
  blocked-worlds:
    - world_nether
    - world_the_end

# Configuration for Staff-Chat
Staff-Chat:
  is-activated: false
  prefix: '&8[&cStaffChat&8] '
  enabled: '&aStaff Chat has been toggled on!'
  disabled: '&cStaff Chat has been toggled off!'
  invalid-permission: '&cYou do not have permission to use this command.'

# Configuration for Anti-CaneNuke
Anti-CaneNuke:
  is-activated: false
  cane-limit: 10                                                     # Maximum number of cane breaks allowed before triggering the limit
  cooldown-time: 60                                                  # Cooldown period in seconds after reaching the cane break limit
  reset-time: 200                                                    # Time period in ticks (20 ticks = 1 second) for resetting the break limit
  cooldown-message: "You are on cooldown for %time% seconds."        # Message shown when player is on cooldown
  limit-exceeded-message: "You have exceeded the cane break limit!"  # Message shown when limit is exceeded

# Configuration for Soft Freeze
SoftFreeze:
  is-activated: true
  invalid-permission: "&cYou do not have permission to use the SoftFreeze command."
  usage:
    - "&6_____________.[ &2SoftFreeze &6]._____________"
    - "&b/softfreeze &3[player]"
  player-not-online: "&cThe player is not online."
  frozen-message: "&a%player% has been frozen successfully."
  frozen-target-message: "&cYou have been soft frozen!"
  unfrozen-message: "&a%player% has been unfrozen."
  unfrozen-target-message: "&cYou have been soft unfrozen!"
  reminder-message: "&eYou have been Soft Frozen. Please do not log off."
  ban-message: "&cYou have been banned for logging out while frozen."


# General Plugin Configuration
plugin-reload: "&aPlugin has been successfully reloaded."
invalid-permission: "&cYou don't have permission to reload the plugin."

# PERMISSIONS
# zyrostaffutils.softfreeze.use
# zyrostaffutils.flybooster.bypass
# zyrostaffutils.antiskilled.bypass
# zyrostaffutils.headrotate.use
# zyrostaffutils.staffchat.use
# zyrostaffutils.staff.alerts
# zyrostaffutils.reload
