name: ZyroStaffUtils
main: me.zyromate.zyrostaffutils.ZyroStaffUtils
version: 1.1
api-version: 1.8.8
author: Zyromate
description: Very cool plugin and somehow works

commands:
  zyrostaffutils:
    description: Base command for ZyroStaffUtils.
    aliases: [zsu, zyrostaffutils]
  staffchat:
    description: Toggles the staff chat on or off.
    aliases: [sc, sct]
  rotate:
    description: Rotate a player's head.
  softfreeze:
    description: Soft freezes a player
    aliases: [sfreeze, softfreeze, softf]

permissions:
  zyrostaffutils.headrotate.use:
    description: Allows a player to rotate other players' heads.
    default: op

  zyrostaffutils.antiskilled.bypass:
    description: Allows a player to bypass the AntiSkilled.
    default: op

  zyrostaffutils.flybooster.bypass:
    description: Allows a player to bypass the FlyBoostLimiter.
    default: op

  zyrostaffutils.reload:
    description: Allows a player to reload the plugin's configuration.
    default: op

  zyrostaffutils.staffchat.use:
    description: Allows a player to use staff chat.
    default: op

  zyrostaffutils.staff.alerts:
    description: Allows receiving staff alerts
    default: op

  zyrostaffutils.softfreeze.use:
    description: Allows a player to use soft freeze
    default: op
